version: '3'

services:
  control-backend:
    image: mitmapps-control-backend:latest
    volumes:
      - ./mitmapps:/app/mitmapps
    ports:
      - "0.0.0.0:90:8080"

  control-frontend:
    depends_on:
      - control-backend
    image: mitmapps-control-frontend:latest
    ports:
      - "0.0.0.0:80:3000"

  mitmproxy:
    image: mitmproxy/mitmproxy:latest
    volumes:
      - ./mitmapps:/app/mitmapps
      - ./mitmproxy_addon:/app/mitmproxy_addon
      - ~/.mitmproxy:/home/mitmproxy/.mitmproxy2
    ports:
      - "0.0.0.0:8080:8080"
    entrypoint: mitmdump -s /app/mitmproxy_addon/mitmapps.py


