version: '3'

services:
  control-backend:
    image: mitmapps/control-backend:latest
    volumes:
      - ./mitmapps:/app/mitmapps
    ports:
      - "0.0.0.0:90:8080"

  control-frontend:
    depends_on:
      - control-backend
    image: mitmapps/control-frontend:latest
    ports:
      - "0.0.0.0:80:3000"

  mitmproxy:
    image: mitmapps/mitmproxy:latest
    volumes:
      - ./mitmapps:/app/mitmapps
      - ./mitmproxy_mods/mitmproxy_addon:/app/mitmproxy_addon
      - ~/.mitmproxy:/home/mitmproxy/.mitmproxy
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8081:8081"
    entrypoint: mitmdump -s /app/mitmproxy_addon/mitmapps.py --set confdir=/home/mitmproxy/.mitmproxy
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
